manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infely # custom nano view
      url-base: https://github.com/infely # custom nano view
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-battery # custom nano view
      remote: infely # custom nano view
      revision: main # custom nano view
  self:
    path: config
